fastlane_version "1.66.0"
default_platform :ios

SLACK_URL = "https://hooks.slack.com/services/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".freeze
FRAMEWORK_NAME = "EasyPeasy".freeze
REPOSITORY_NAME = "EasyPeasy".freeze

platform :ios do
    desc "Release new version"
    lane :release do |options|
        target_version = options[:version]
        raise "The version is missed. Use `fastlane release version:{version_number}`.`" if target_version.nil?
  
        ensure_git_branch
        ensure_git_status_clean
        
        # Increment version
        increment_version_number(version_number: target_version)  
        
        # Create Carthage framework
        Actions.sh("cd .. && carthage build --no-skip-current && carthage archive #{FRAMEWORK_NAME}")
        framework_binary = File.join(File.expand_path('../..', __FILE__),"#{FRAMEWORK_NAME}.framework.zip")
        raise "No binary found to upload #{framework_binary}" if File.file?(framework_binary) == false

        git_add
        git_commit(path: ".", message: "New release version bump")

        # Create release tag
        push_to_git_remote
        
        set_github_release(
            repository_name: "LootApp/#{REPOSITORY_NAME}",
            api_token: ENV['GITHUB_API_TOKEN'],
            tag_name: target_version,
            upload_assets: [ framework_binary ],
            name: target_version,
            description: "Release of #{target_version}"
        )

        File.delete(framework_binary)
    end
end